name: Node CI
on: [push]
jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Install dependencies
          run: npm install
        - name: Run tests
          run: npm run test
        - name: Run linter
          run: npm run lint
        - name: Test & publish code coverage
          uses: paambaati/codeclimate-action@v5.0.0
          with:
            debug: true